version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn fireout.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/html/static/
      - media_volume:/var/www/html/media/
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - ./prod.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/www/html/static/
      - media_volume:/var/www/html/media/
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
