version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: fireout:latest
    command: python3.6 manage.py runserver 0.0.0.0:8000
    ports:
      - "127.0.0.1:8083:8000"
    depends_on:
      - db
